### ISSUE TITLE
Display info already present in the associated excel sheet

### ISSUE THREAD

**Issue by bes827** [Sven-Bo/data-entry-form-pysimplegui#2]
I have been looking for something similar to what you did (ie a mini redcap like data entry form that is decentralized and is standalone). 
Thanks a lot for writing this script and making it available for everyone. 

I have two more features in mind and was wondering if you would think about adding them (or provide some thoughts/guidance on how to code them):
- add a navigation option where we can go forward and backwards through the rows and enter data
- read/load the data already entered in the associated excel sheet and give the option to edit them.

**Comment by Sven-Bo** [comment]
Thank you for watching the video. Your questions are great, but finding the time to answer them is difficult. Kindly understand that I receive many requests for individual solutions or modifications. That said, you might want to join our Discord server ( https://pythonandvba.com/discord ) and post your question there. Thanks for your understanding. Happy Coding!
